# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dsa_get_metric_mean <- function(head_df, chest_df, hands_df, legs_df, index) {
    .Call(`_dsa_rda_dsa_get_metric_mean`, head_df, chest_df, hands_df, legs_df, index)
}

dsa_get_metric_var <- function(head_df, chest_df, hands_df, legs_df, index, metric_mean) {
    .Call(`_dsa_rda_dsa_get_metric_var`, head_df, chest_df, hands_df, legs_df, index, metric_mean)
}

dsa_get_metrics_covar <- function(head_df, chest_df, hands_df, legs_df, index_1, index_2, metric_mean_1, metric_mean_2) {
    .Call(`_dsa_rda_dsa_get_metrics_covar`, head_df, chest_df, hands_df, legs_df, index_1, index_2, metric_mean_1, metric_mean_2)
}

