// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_metric_mean
double get_metric_mean(const DataFrame& head_df, const DataFrame& chest_df, const DataFrame& hands_df, const DataFrame& legs_df, const int index);
RcppExport SEXP _darksoulsarmor_get_metric_mean(SEXP head_dfSEXP, SEXP chest_dfSEXP, SEXP hands_dfSEXP, SEXP legs_dfSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type head_df(head_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type chest_df(chest_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type hands_df(hands_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type legs_df(legs_dfSEXP);
    Rcpp::traits::input_parameter< const int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(get_metric_mean(head_df, chest_df, hands_df, legs_df, index));
    return rcpp_result_gen;
END_RCPP
}
// get_metric_var
double get_metric_var(const DataFrame& head_df, const DataFrame& chest_df, const DataFrame& hands_df, const DataFrame& legs_df, const int index, const double metric_mean);
RcppExport SEXP _darksoulsarmor_get_metric_var(SEXP head_dfSEXP, SEXP chest_dfSEXP, SEXP hands_dfSEXP, SEXP legs_dfSEXP, SEXP indexSEXP, SEXP metric_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type head_df(head_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type chest_df(chest_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type hands_df(hands_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type legs_df(legs_dfSEXP);
    Rcpp::traits::input_parameter< const int >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const double >::type metric_mean(metric_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(get_metric_var(head_df, chest_df, hands_df, legs_df, index, metric_mean));
    return rcpp_result_gen;
END_RCPP
}
// get_metrics_covar
double get_metrics_covar(const DataFrame& head_df, const DataFrame& chest_df, const DataFrame& hands_df, const DataFrame& legs_df, const int index_1, const int index_2, const double metric_mean_1, const double metric_mean_2);
RcppExport SEXP _darksoulsarmor_get_metrics_covar(SEXP head_dfSEXP, SEXP chest_dfSEXP, SEXP hands_dfSEXP, SEXP legs_dfSEXP, SEXP index_1SEXP, SEXP index_2SEXP, SEXP metric_mean_1SEXP, SEXP metric_mean_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type head_df(head_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type chest_df(chest_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type hands_df(hands_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type legs_df(legs_dfSEXP);
    Rcpp::traits::input_parameter< const int >::type index_1(index_1SEXP);
    Rcpp::traits::input_parameter< const int >::type index_2(index_2SEXP);
    Rcpp::traits::input_parameter< const double >::type metric_mean_1(metric_mean_1SEXP);
    Rcpp::traits::input_parameter< const double >::type metric_mean_2(metric_mean_2SEXP);
    rcpp_result_gen = Rcpp::wrap(get_metrics_covar(head_df, chest_df, hands_df, legs_df, index_1, index_2, metric_mean_1, metric_mean_2));
    return rcpp_result_gen;
END_RCPP
}
// all_armor_combinations
void all_armor_combinations(const DataFrame& head_df, const DataFrame& chest_df, const DataFrame& hands_df, const DataFrame& legs_df, DataFrame& full_df);
RcppExport SEXP _darksoulsarmor_all_armor_combinations(SEXP head_dfSEXP, SEXP chest_dfSEXP, SEXP hands_dfSEXP, SEXP legs_dfSEXP, SEXP full_dfSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type head_df(head_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type chest_df(chest_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type hands_df(hands_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type legs_df(legs_dfSEXP);
    Rcpp::traits::input_parameter< DataFrame& >::type full_df(full_dfSEXP);
    all_armor_combinations(head_df, chest_df, hands_df, legs_df, full_df);
    return R_NilValue;
END_RCPP
}
// optimize_armor_combinations
DataFrame optimize_armor_combinations(const int starting_loop_size, const int max_output_size, const double base_weight, const double load, const double load_motf, const double load_threshold, const double load_threshold_motf, const int motf_index, const bool wolf, const NumericVector& minima, const DataFrame& head_df, const DataFrame& chest_df, const DataFrame& hands_df, const DataFrame& legs_df);
RcppExport SEXP _darksoulsarmor_optimize_armor_combinations(SEXP starting_loop_sizeSEXP, SEXP max_output_sizeSEXP, SEXP base_weightSEXP, SEXP loadSEXP, SEXP load_motfSEXP, SEXP load_thresholdSEXP, SEXP load_threshold_motfSEXP, SEXP motf_indexSEXP, SEXP wolfSEXP, SEXP minimaSEXP, SEXP head_dfSEXP, SEXP chest_dfSEXP, SEXP hands_dfSEXP, SEXP legs_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type starting_loop_size(starting_loop_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type max_output_size(max_output_sizeSEXP);
    Rcpp::traits::input_parameter< const double >::type base_weight(base_weightSEXP);
    Rcpp::traits::input_parameter< const double >::type load(loadSEXP);
    Rcpp::traits::input_parameter< const double >::type load_motf(load_motfSEXP);
    Rcpp::traits::input_parameter< const double >::type load_threshold(load_thresholdSEXP);
    Rcpp::traits::input_parameter< const double >::type load_threshold_motf(load_threshold_motfSEXP);
    Rcpp::traits::input_parameter< const int >::type motf_index(motf_indexSEXP);
    Rcpp::traits::input_parameter< const bool >::type wolf(wolfSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type minima(minimaSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type head_df(head_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type chest_df(chest_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type hands_df(hands_dfSEXP);
    Rcpp::traits::input_parameter< const DataFrame& >::type legs_df(legs_dfSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_armor_combinations(starting_loop_size, max_output_size, base_weight, load, load_motf, load_threshold, load_threshold_motf, motf_index, wolf, minima, head_df, chest_df, hands_df, legs_df));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_darksoulsarmor_get_metric_mean", (DL_FUNC) &_darksoulsarmor_get_metric_mean, 5},
    {"_darksoulsarmor_get_metric_var", (DL_FUNC) &_darksoulsarmor_get_metric_var, 6},
    {"_darksoulsarmor_get_metrics_covar", (DL_FUNC) &_darksoulsarmor_get_metrics_covar, 8},
    {"_darksoulsarmor_all_armor_combinations", (DL_FUNC) &_darksoulsarmor_all_armor_combinations, 5},
    {"_darksoulsarmor_optimize_armor_combinations", (DL_FUNC) &_darksoulsarmor_optimize_armor_combinations, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_darksoulsarmor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
