# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

all_armor_combinations <- function(head_df, chest_df, hands_df, legs_df, full_df) {
    invisible(.Call(`_darksoulsarmor_all_armor_combinations`, head_df, chest_df, hands_df, legs_df, full_df))
}

optimal_armor_combinations <- function(starting_loop_size, max_output_size, base_weight, load, load_motf, load_threshold, load_threshold_motf, motf_index, wolf, minima, head_df, chest_df, hands_df, legs_df) {
    .Call(`_darksoulsarmor_optimal_armor_combinations`, starting_loop_size, max_output_size, base_weight, load, load_motf, load_threshold, load_threshold_motf, motf_index, wolf, minima, head_df, chest_df, hands_df, legs_df)
}

