# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_metric_mean <- function(head_df, chest_df, hands_df, legs_df, index) {
    .Call(`_darksoulsarmor_get_metric_mean`, head_df, chest_df, hands_df, legs_df, index)
}

get_metric_var <- function(head_df, chest_df, hands_df, legs_df, index, metric_mean) {
    .Call(`_darksoulsarmor_get_metric_var`, head_df, chest_df, hands_df, legs_df, index, metric_mean)
}

get_metrics_covar <- function(head_df, chest_df, hands_df, legs_df, index_1, index_2, metric_mean_1, metric_mean_2) {
    .Call(`_darksoulsarmor_get_metrics_covar`, head_df, chest_df, hands_df, legs_df, index_1, index_2, metric_mean_1, metric_mean_2)
}

all_armor_combinations <- function(head_df, chest_df, hands_df, legs_df, full_df) {
    invisible(.Call(`_darksoulsarmor_all_armor_combinations`, head_df, chest_df, hands_df, legs_df, full_df))
}

optimize_armor_combinations <- function(starting_loop_size, max_output_size, base_weight, load, load_motf, load_threshold, load_threshold_motf, motf_index, wolf, minima, head_df, chest_df, hands_df, legs_df) {
    .Call(`_darksoulsarmor_optimize_armor_combinations`, starting_loop_size, max_output_size, base_weight, load, load_motf, load_threshold, load_threshold_motf, motf_index, wolf, minima, head_df, chest_df, hands_df, legs_df)
}

